spring:
  data:
    mongodb:
      uri: mongodb://localhost/izard
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-null-for-primitives: true

endpoints:
  default:
    enabled: true
